#SPDX-License-Identifier: MIT-0
---
# tasks file for sample-role

  - name: print msg
    debug:
     msg: "this role task"

  - name: print msg
    debug:
     msg: "{{text}}"

  - name: Install Apache2
    apt:
     name: apache2
     state: present
     update_cache: yes


  - name: copy index.html       
    copy:
     src: index.html
     dest: /var/www/html/index.html

   